version: '3.7'
services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v0.29.0
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - ${MEILI_PORT:-7700}:7700
    networks:
      - meilisearch
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://meilisearch:7700/health"]
      retries: 3
      timeout: 5s
    
networks:
  meilisearch:
    driver: bridge
