version: '3.7'
services:
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.0.2
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    hostname: meiliepg
    ports:
      - ${MEILI_PORT:-7700}:7700
    networks:
      - meilisearch
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://meiliepg:7700/health"]
      retries: 3
      timeout: 5s
  recorder:
    container_name: recorder
    build:
      context: ./recorder
      dockerfile: Dockerfile
    depends_on:
      meilisearch:
        condition: service_healthy
    
networks:
  meilisearch:
    driver: bridge
